const rooms=[
 {id:'master',name:'Master Suite',label:'The Villa’s Finest Bedroom',meta:'Ground Floor • Super King • En-suite • Private Terrace • Pool View',desc:'The luxurious Master Suite enjoys direct access to a private terrace overlooking the lagoon-style swimming pool and tropical gardens. Featuring a sumptuous Super King bed, elegant furnishings and a spacious en-suite bathroom, it provides the perfect sanctuary after a day in the Marbella sunshine.',features:['🛏 Super King Bed','🚿 Luxury En-suite','🌴 Private Terrace','🏊 Pool Views','❄️ Air Conditioning','📶 High-Speed Wi-Fi'],count:7},
 {id:'bedroom-two',name:'Bedroom Two',label:'Pool View Suite',meta:'Ground Floor • Super King • En-suite • Terrace Access',desc:'A spacious Super King bedroom finished in warm contemporary tones, offering generous proportions, a luxurious en-suite bathroom and beautiful views across the gardens.',features:['🛏 Super King Bed','🚿 En-suite Bathroom','🌴 Garden Views','☀️ Terrace Access','❄️ Air Conditioning','📶 Wi-Fi'],count:8},
 {id:'bedroom-three',name:'Bedroom Three',label:'Deluxe Suite',meta:'Ground Floor • Super King • En-suite • Spacious Layout',desc:'One of the villa’s largest bedrooms, complete with a Super King bed, elegant décor and an impressive en-suite bathroom. The generous floor space makes it ideal for longer stays or guests wanting a little extra luxury.',features:['🛏 Super King Bed','🚿 En-suite Bathroom','🌿 Spacious Layout','❄️ Air Conditioning','📶 Wi-Fi','🧳 Generous Storage'],count:8},
 {id:'bedroom-four',name:'Bedroom Four',label:'Garden View Room',meta:'First Floor • Double • Garden View • Bathroom Access',desc:'A beautifully bright double bedroom overlooking the mature tropical gardens, with calm interiors, comfortable furnishings and a peaceful atmosphere for relaxed Marbella mornings.',features:['🛏 Double Bed','🌴 Garden Views','❄️ Air Conditioning','📶 Wi-Fi','🛁 Bathroom Access','☀️ Natural Light'],count:7},
 {id:'bedroom-five',name:'Bedroom Five',label:'Twin Balcony Room',meta:'First Floor • Twin Room • Private Balcony • Garden View',desc:'A bright and spacious twin bedroom with two comfortable single beds and French doors opening onto a private first-floor balcony. Perfect for friends sharing or younger members of the group.',features:['🛏 Two Single Beds','☀️ Private Balcony','🌴 Garden Views','❄️ Air Conditioning','📶 Wi-Fi','🛋 Extra Space'],count:4},
 {id:'garden-room',name:'Garden Room',label:'Private Garden Suite',meta:'Garden Level • Twin Room • En-suite • Private Setting',desc:'Located on the garden level, this peaceful twin room offers extra privacy and its own contemporary en-suite bathroom. Ideal for guests seeking a quieter space while remaining only moments from the pool and gardens.',features:['🛏 Two Single Beds','🚿 En-suite Bathroom','🌿 Garden Level','❄️ Air Conditioning','📶 Wi-Fi','🌴 Private Setting'],count:1,placeholders:5}
];
const roomsEl=document.getElementById('rooms');
let allImages=[];let currentIndex=0;
function imgPath(id,i){return `assets/${id}-${String(i).padStart(2,'0')}.webp`}
rooms.forEach(room=>{
 const imgs=Array.from({length:room.count},(_,i)=>imgPath(room.id,i+1)); allImages.push(...imgs);
 const placeholders = Array.from({length:room.placeholders||0},(_,i)=>`<div class="photo-placeholder"><span>Photo ${i+2}</span><small>Coming soon</small></div>`).join('');
 const section=document.createElement('article'); section.className='room'; section.id=room.id;
 section.innerHTML=`<div class="room-media"><img class="main-img" src="${imgs[0]}" alt="${room.name}" loading="lazy"><div class="thumbs">${imgs.map((src,i)=>`<img src="${src}" alt="${room.name} image ${i+1}" loading="lazy">`).join('')}${placeholders}</div></div><div class="room-copy"><span class="eyebrow">${room.label}</span><h3>${room.name}</h3><div class="meta">${room.meta}</div><p>${room.desc}</p><div class="features">${room.features.map(f=>`<span>${f}</span>`).join('')}</div>${room.id==='garden-room'?'<p class="meta" style="margin-top:22px">Five additional Garden Room photos have been reserved and can be added when ready.</p>':''}</div>`;
 roomsEl.appendChild(section);
});

document.querySelectorAll('.thumbs img').forEach(img=>{img.addEventListener('click',e=>{const main=e.target.closest('.room-media').querySelector('.main-img'); main.src=e.target.src;});});
document.querySelectorAll('.main-img,.masonry img').forEach(img=>img.addEventListener('click',()=>openLightbox(img.src)));
const lb=document.getElementById('lightbox'), lbImg=document.getElementById('lightboxImg');
function openLightbox(src){allImages=[...document.querySelectorAll('.main-img,.thumbs img,.masonry img')].map(i=>i.src);currentIndex=allImages.indexOf(src); if(currentIndex<0)currentIndex=0; lbImg.src=allImages[currentIndex]; lb.classList.add('open');}
function move(n){currentIndex=(currentIndex+n+allImages.length)%allImages.length; lbImg.src=allImages[currentIndex];}
document.getElementById('close').onclick=()=>lb.classList.remove('open');document.getElementById('prev').onclick=()=>move(-1);document.getElementById('next').onclick=()=>move(1);document.addEventListener('keydown',e=>{if(!lb.classList.contains('open'))return;if(e.key==='Escape')lb.classList.remove('open');if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);});
window.addEventListener('scroll',()=>document.getElementById('nav').classList.toggle('scrolled',window.scrollY>60));
